# Структура проекта:
# lib/
#   ├── main.dart
#   ├── models/
#   │   └── task_model.dart
#   ├── services/
#   │   └── storage_service.dart
#   ├── screens/
#   │   └── todo_screen.dart
#   ├── viewmodels/
#   │   └── todo_view_model.dart
#   ├── views/
#   │   ├── screens/
#   │   └── widgets/
#   │       ├── cards/
#   │       ├── dialogs/
#   │       └── items/
#   └── assets/
#       └── icons/
#           ├── bookmark.png
#           └── calendar.png

name: todo_app
description: A Flutter Todo application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/